version: '3.9'
services:
  backend:
    container_name: togo_container
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    build: .
    ports:
      - 8000:8080
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - backend

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 1234:${DATABASE_PORT}
    networks:
      - backend

# Networks to be created to facilitate communication between containers
networks:
  backend:
    name: 'backend'